cursor #000000
cursor_text_color #000000

foreground            #000000
background            #fff7df
selection_foreground  #fff7df
selection_background  #666666
url_color             #fff7df

color0   #000000
color1   #f26d60
color2   #54bf42
color3   #ffdf3f
color4   #fff6dd
color5   #fffcf4
color6   #fff7df
color7   #474644
color8   #d8d7d3
color9   #ff8a7f
color10  #86ff72
color11  #ffe14c
color12  #fff6db
color13  #fffcf4
color14  #fffbef
color15  #fffdf9
