# vim:ft=kitty
## name: vnkjd light
## author: vnkjd
## blurb: Light kitty theme with vnkjd colors


# The basic colors
foreground #18130d
background #fffaf0
selection_foreground #18130d
selection_background #ff9900

# Cursor colors
cursor #ff9900
cursor_text_color #18130d

# Scrollbar colors
scrollbar_handle_color #a89a84
scrollbar_track_color #f4e8d4

# URL color when hovering with mouse
url_color #a35b00

# Kitty window border colors
active_border_color #ff9900
inactive_border_color #a89a84
bell_border_color #bf6256

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground #18130d
active_tab_background #ff9900
inactive_tab_foreground #18130d
inactive_tab_background #f4e8d4
tab_bar_background #fffaf0

# Colors for marks (marked text in the terminal)
mark1_foreground #fffaf0
mark1_background #4f719c
mark2_foreground #fffaf0
mark2_background #765d8d
mark3_foreground #fffaf0
mark3_background #3d7772

# The 16 terminal colors
# black
color0 #18130d
color8 #a89a84

# red
color1 #a64c43
color9 #bf6256

# green
color2 #536f42
color10 #6d8956

# yellow
color3 #a35b00
color11 #bd7200

# blue
color4 #4f719c
color12 #6788ae

# magenta
color5 #765d8d
color13 #8e71a4

# cyan
color6 #3d7772
color14 #568f89

# white
color7 #746653
color15 #fffaf0
