# vim:ft=kitty
## name: vnkjd dark
## author: vnkjd
## blurb: Dark kitty theme with vnkjd colors


# The basic colors
foreground #f4efe6
background #080706
selection_foreground #18130d
selection_background #ffaf00

# Cursor colors
cursor #ffaf00
cursor_text_color #18130d

# Scrollbar colors
scrollbar_handle_color #8a7b67
scrollbar_track_color #18140e

# URL color when hovering with mouse
url_color #ffaf00

# Kitty window border colors
active_border_color #ffaf00
inactive_border_color #8a7b67
bell_border_color #f28a78

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground #18130d
active_tab_background #ffaf00
inactive_tab_foreground #f4efe6
inactive_tab_background #18140e
tab_bar_background #080706

# Colors for marks (marked text in the terminal)
mark1_foreground #18130d
mark1_background #7193bd
mark2_foreground #18130d
mark2_background #a483bd
mark3_foreground #18130d
mark3_background #609e98

# The 16 terminal colors
# black
color0 #080706
color8 #8a7b67

# red
color1 #d96c5f
color9 #f28a78

# green
color2 #77945f
color10 #9bbd7a

# yellow
color3 #ffaf00
color11 #ffc24a

# blue
color4 #7193bd
color12 #94b6df

# magenta
color5 #a483bd
color13 #c3a3dc

# cyan
color6 #609e98
color14 #82beb7

# white
color7 #f4efe6
color15 #fffaf0
