[colors]
background = '#ffffff'
foreground = '#232222'

cursor_bg = '#cc5200'
cursor_fg = '#ffffff'
cursor_border = '#cc5200'

selection_bg = '#cc5200'
selection_fg = '#232222'

ansi = ['#0d0d0d', '#c10900', '#1b9900', '#f4c900', '#d65600', '#ffcead', '#cc5200', '#393634']
brights = ['#ada8a4', '#f40b00', '#27e000', '#ffd100', '#ea5e00', '#ffcead', '#ffb27f', '#fff8f4']
