foreground = #f4efe6
background = #080706

cursor-color = #ff9900
cursor-text = #18130d
selection-foreground = #18130d
selection-background = #ff9900

palette = 0=#080706
palette = 1=#d96c5f
palette = 2=#77945f
palette = 3=#ff9900
palette = 4=#7193bd
palette = 5=#a483bd
palette = 6=#609e98
palette = 7=#f4efe6
palette = 8=#8a7b67
palette = 9=#f28a78
palette = 10=#9bbd7a
palette = 11=#ffb340
palette = 12=#94b6df
palette = 13=#c3a3dc
palette = 14=#82beb7
palette = 15=#fffaf0
palette = 231=#fffaf0
