foreground = #18130d
background = #fffaf0

cursor-color = #ff9900
cursor-text = #18130d
selection-foreground = #18130d
selection-background = #ff9900

palette = 0=#18130d
palette = 1=#a64c43
palette = 2=#536f42
palette = 3=#a35b00
palette = 4=#4f719c
palette = 5=#765d8d
palette = 6=#3d7772
palette = 7=#746653
palette = 8=#a89a84
palette = 9=#bf6256
palette = 10=#6d8956
palette = 11=#bd7200
palette = 12=#6788ae
palette = 13=#8e71a4
palette = 14=#568f89
palette = 15=#fffaf0
palette = 231=#fffaf0
