[colors]
background = '#ffffff'
foreground = '#000000'

cursor_bg = '#ffffff'
cursor_fg = '#ffffff'
cursor_border = '#ffffff'

selection_bg = '#cc5200'
selection_fg = '#000000'

ansi = ['#000000', '#f26060', '#5ebf42', '#ffd93f', '#ffffff', '#ffffff', '#FFFFFF', '#474444']
brights = ['#d8d3d3', '#ff7f7f', '#91ff72', '#ffdc4c', '#ffffff', '#ffffff', '#ffffff', '#fff9f9']
