[colors]
background = '#f6fafe'
foreground = '#181c1f'

cursor_bg = '#1b6585'
cursor_fg = '#f6fafe'
cursor_border = '#1b6585'

selection_bg = '#c3e8ff'
selection_fg = '#181c1f'

ansi = ['#0f1417', '#7e052c', '#00630b', '#9f9500', '#16688b', '#afd9eb', '#1b6585', '#222425']
brights = ['#6c6f71', '#c04163', '#129220', '#aca200', '#20779f', '#afd9eb', '#6898ac', '#c1c5c7']
