[colors]
background = '#fff7df'
foreground = '#000000'

cursor_bg = '#fff7df'
cursor_fg = '#fff7df'
cursor_border = '#fff7df'

selection_bg = '#cc5200'
selection_fg = '#000000'

ansi = ['#000000', '#f26d60', '#54bf42', '#ffdf3f', '#fff6dd', '#fffcf4', '#fff7df', '#474644']
brights = ['#d8d7d3', '#ff8a7f', '#86ff72', '#ffe14c', '#fff6db', '#fffcf4', '#fffbef', '#fffdf9']
